# Input/Output settings
input: "input_files/nohup.out"
output_log: "operations_above_threshold.csv"
csv_output: "dlc_stats.csv"

# Analysis settings
threshold: 5000
top_n: 10


# Time parsing
time_format: "%Y-%m-%d %H:%M:%S.%f"


# Time Window (Optional)
# If these are null, the script processes the whole file
start_time: "2026-01-29 13:40:27.000"
end_time: "2026-01-29 19:01:35.000"
keep_reduced: true
